### ISSUE TITLE
Add sop frontend

### ISSUE THREAD

**Issue by link2xt** [rpgp/rpgp#110]
There is a standard CLI interface: https://datatracker.ietf.org/doc/html/draft-dkg-openpgp-stateless-cli-08
Latest version of the draft is at https://dkg.gitlab.io/openpgp-stateless-cli/

Implementing it will allow to run [OpenPGP interoperability test suite](https://tests.sequoia-pgp.org/)

**Comment by teythoon** [comment]
Implementing the Rust SOP interface (https://docs.rs/sop) now gives you the CLI frontend for free.

**Comment by dignifiedquire** [comment]
@dkg yes, it is on my todo list, but unfortunately so are many other things 😭

**Comment by dkg** [comment]
i know the feeling, @dignifiedquire -- you have my sympathies.  Have things shifted around any that you might be able to take a crack at it?  #125 points to some stumbling blocks that @teythoon ran into when trying to write a sop-rs backend.  And even a partial implementation is a useful starting point.

Or, maybe some other `rpgp` dev might be interested in working on creating this mapping?  Maybe it'd be a job for someone coming up to speed on the project?

**Comment by hko-s** [comment]
I've spent a bit of time with https://crates.io/crates/sop, and the "OpenPGP interoperability test suite", both of which are excellent!

The result of my hacking so far is the experimental and still somewhat incomplete https://crates.io/crates/rsop

**Comment by hpk42** [comment]
No need to keep this issue open anymore, phew! thanks a lot @hko-s  @dignifiedquire and @link2xt for pushing through all the issues/PRs in the last weeks! :partying_face: 
And to @teythoon for the base work and the integration into https://tests.sequoia-pgp.org/ :purple_heart: 
and of course to @dkg for persevering and long-running background work!
