### ISSUE TITLE
Encrypting file with public key

### ISSUE THREAD

**Issue by fenuks** [rpgp/rpgp#112]
Hello, I need to encrypt data with public key and save it to the file.

I found snippet in tests that exercises encryption with private key, I adapted it a bit, and ended up with something like this (where `PUBLIC_KEY` is my PGP key using RSA2048):

```rust
fn encrypt(text: &str) {
    let mut rng = thread_rng();
    let (key, _headers) = SignedPublicKey::from_string(PUBLIC_KEY).expect("Failed to parse key");
    let ciphertext = key.encrypt(&mut rng, text.as_bytes()).expect("Failed to encrypt data");
}
```

That seems to work, but I cannot figure out, how to write this ciphertext to the file, that can be later decrypted with GnuPG. I tried naively to iterate over ciphertext vector and write bytes, but that doesn't work.

```
gpg: no valid OpenPGP data found.
gpg: decrypt_message failed: Unknown system error
```
I would be really grateful for a hint what I am missing.

**Comment by rk0n** [comment]
I don't know how you tried to save the ciphertext as file because you didn't provide any code and keys to debug it but you can use this snippet that worked for me:

```rust
let message: String = fs::read_to_string(message_file_path)?.parse()?;

let lit_msg = Message::new_literal_bytes("", message.as_bytes());
let mut rng = thread_rng();

let encrypted_msg = lit_msg
    .sign(
        &secret_key,
        || secret_key_passphrase.to_string(),
        hash_algorithm,
    )
    .and_then(|msg| msg.compress(compression_algorithm))
    .and_then(|msg| msg.encrypt_to_keys(&mut rng, symmetric_key_algorithm, &[&pub_key]));

let msg = encrypted_msg?;
let encoded_msg: Vec<u8> = msg.to_armored_bytes(None)?;

let encoded_msg: Vec<u8> = ciphertext?.to_armored_bytes(None)?;
std::fs::write(ENCRYPTED_FILE_PATH).expect("Failed to save encrypted message to file");
```

**Comment by fenuks** [comment]
Thank you for reply. I ended up solving it different way, but hopefully somebody in future might find it useful. I suppose this issue can be closed now.

**Comment by dignifiedquire** [comment]
> with gpg as the sign process is not the same as described in RFC:

@rk0n What do you mean with that? Signing has been exactly implemented to match the RFC, so I am not what difference you are referring to here? 
(Note: these are low level apis to build up the pgp packets as described in the RFC, so you have to make sure to construct them in the right form atm)
