### ISSUE TITLE
Go through API review notes regarding SOP-support for rpgp

### ISSUE THREAD

**Issue by hpk42** [rpgp/rpgp#125]
SOP is an evolving standard way to run interop pgp tests, driven by the nice https://sequoia-pgp.org/ folks. 
Here are some notes from @teythoon while he tried to write a sop backend for rpgp. 
https://gitlab.com/sequoia-pgp/rpgp-sop/-/blob/hack/notes.org

**Comment by dignifiedquire** [comment]
Closing this, as a lot of feedback was processed, including the integration into rpgpie which implements the full sop interface now
