### ISSUE TITLE
Message::verify() succeeds when gpg does not

### ISSUE THREAD

**Issue by skulthe** [rpgp/rpgp#126]
I'm trying to verify a message has been signed by the given public key. To test this I tried modifying the contents of the ASCII message, expecting `Message::verify()` to produce an error, but it did not. I then used `gpg --verify signed_message.sig`, which produced 
```
gpg: CRC error; 2E424B - 1BE5BF
gpg: no signature found
gpg: the signature could not be verified.
```
 
Code Snippet:
```
let message = Message::from_armor_single(data).unwrap().0;
let verify = &message.verify(&public_key);
```
When I `dbg!(message)` I can see it is `Message::Compressed`. As a test I produced a new signed message using `gpg --output signed_message.sig --sign --compress-level 0 --armor message.toml`. This produced a `Message::Signed` and after modifying the contents of the message, `Message::verify()` produced an `Error` as expected.

**Comment by dignifiedquire** [comment]
Any chance you could provide a version of the modified and unmodified messages where you are seeing this difference

**Comment by skulthe** [comment]
Hi, it seems earlier I must have used some of the functions incorrectly which might have caused this error.
However, on trying again, the issue is not reproducible anymore. So it looks like signature verification works as
expected.
