### ISSUE TITLE
Update curve25519 crate?

### ISSUE THREAD

**Issue by link2xt** [rpgp/rpgp#127]
`curve25519-dalek` has been forked into `curve25519-dalek-ng`: https://twitter.com/hdevalence/status/1356831666124197890
It has not much changes yet, but updates `rand` and `rand_core` packages.

We still can't update to `curve25519-dalek-ng` because `rpgp` depends on `curve25519-dalek` indirectly through `ed25519-dalek` which has not been forked and still depends on version 3 of `curve25519-dalek`, while the fork has bumped the version to 4. See related issue https://github.com/zkcrypto/curve25519-dalek-ng/issues/8

**Comment by dignifiedquire** [comment]
Worked around this on `master`, due to the dependency complications we can't switch to dalek-ng for now
