### ISSUE TITLE
Publish latest code to crates.io

### ISSUE THREAD

**Issue by willemml** [rpgp/rpgp#132]
I am currently developing and application using this crate and need to access the `signature` field of the `StandaloneSignature` struct, which is available in the master branch but not yet published to crates.io which means that although I can use the `git` cargo dependency specification I then can't publish to crates.io. Other ways around this for me are to serialize and then deserialize the signature (which has its own problems and seems slow) or using `std::mem::transmute` (which is very unsafe and therefore not viable for my purposes.

**Comment by willemml** [comment]
I did find a safe way around this: 
```rust
let message = pgp::Message::from_string(message_string).unwrap().0;
if let pgp::composed::message::Message::Signed {
    message,
    one_pass_signature,
    signature,
} = message { /* use signature here */ }
```

**Comment by dignifiedquire** [comment]
new release is out

**Comment by willemml** [comment]
Awesome, thanks!
