### ISSUE TITLE
Find new ed25519 implementation 

### ISSUE THREAD

**Issue by dignifiedquire** [rpgp/rpgp#191]
Unfortunately https://github.com/dalek-cryptography/ed25519-dalek is unmaintained, bringing in old dependencies, and no sight of updating in security related issues likely.

Possible alternatives

- https://github.com/jedisct1/rust-ed25519-compact
- ?

Ref https://github.com/rustsec/advisory-db/pull/1361

**Comment by dignifiedquire** [comment]
@tarcieri do you happen to know of alternatives/maintained forks?

**Comment by tarcieri** [comment]
I think @rozbb has commit access to dalek and may potentially be able to move things along.

Beyond that, there's `ed25519-compact` as you mentioned, and experimental libraries like `crrl`.

**Comment by dignifiedquire** [comment]
@tarcieri could we potentially not just fork the dalek crates into rustrcrypto and start maintaining them from there? I am not super excited to switch to an entirely new version tbh.

**Comment by tarcieri** [comment]
If we have to. I'm still trying to see if any of the current maintainers of the Dalek crates can pick up the review work in the meantime.
