### ISSUE TITLE
Proposal to Add an example

### ISSUE THREAD

**Issue by granitDev** [rpgp/rpgp#200]
I found using the library very difficult given the lack of examples. I created a simple project detailing how to use the library in a real way, that is, a practical way that it actually gets used in a setting I had to implement it in.

I wanted to propose that this example be added to the examples. Here is the link to my repository:
https://github.com/granitDev/rPGP-Working-Example

**Comment by dignifiedquire** [comment]
very cool, would you like to make a PR?
