### ISSUE TITLE
How to sign a message? (I need help)

### ISSUE THREAD

**Issue by Myzel394** [rpgp/rpgp#206]
Hey, so I'm new to this package and generally new to Rust. Let's say I have a private key and a message I want to sign, how do I do that?

Here's my code so far

```rust
const PRIVATE_KEY: &str = "<private key>";

#[tokio::main]
async fn main() {
    let message = "Hello.".to_str();
}
```

Yeah I really don't know how to start. I took a look at the tests, but I honestly don't understand them. Can you point me to the right direction on how to start?

**Comment by dfabregat** [comment]
Hi @Myzel394, maybe the examples in this repo can be of help: https://github.com/granitDev/rPGP-Working-Examples
