### ISSUE TITLE
Publish security audit in this repository

### ISSUE THREAD

**Issue by missytake** [rpgp/rpgp#226]
In 2019, this library was security-audited - I still have the PDF around. I think the audit was never published. Are you interested in adding the report to this repository?

**Comment by dignifiedquire** [comment]
Maybe we can add it to the wiki? I am not a fan of adding pdfs to the source code

**Comment by missytake** [comment]
Nevermind, we published the audit on our website: https://delta.chat/assets/blog/2019-first-security-review.pdf

Feel free to link to it, or to https://web.archive.org/web/20230328224811/https://delta.chat/assets/blog/2019-first-security-review.pdf
