### ISSUE TITLE
Is there any function for encrypt message, somthing like Encrypt in Go's gpg?

### ISSUE THREAD

**Issue by RickSKy** [rpgp/rpgp#227]
Go's gpg has Encrypt function which encrypt message and sign the message in pgp format  https://pkg.go.dev/golang.org/x/crypto/openpgp#Encrypt. It will be nice to has this function. Is there any plan for that?

**Comment by RickSKy** [comment]
it works, thanks!  I try to call sign,compress,encrypt_to_keys in order, it is compat for go's Encrypt. Maybe Encrypt can help users who doesn't care about gpg's working detail, and only use a configure struct like SignatureConfigBuilder

**Comment by dignifiedquire** [comment]
@RickSKy currently the whole API is very low level, bug I agree it would be great to have a higher level API in general
