### ISSUE TITLE
Signature verification broken in 0.10

### ISSUE THREAD

**Issue by phyber** [rpgp/rpgp#232]
Hi,

I’m using the `StandaloneSignature::verify` function to verify signatures against a public key and its subkeys. 0.10 seems to have added some returns that don’t look correct in various verification functions.

For example:

https://github.com/rpgp/rpgp/blob/a463cca1cb2bbefe4bb3148babee3685a06a14a6/src/packet/signature/types.rs#L90-L91

Why is this function now returning `Ok(())` when its comment says it’s unable to verify the signature? How should a caller of this function now know if `verify` actually succeeded?

Perhaps I’m just holding the library incorrectly, but 0.9 verifies signatures in an expected way.

Thanks,

**Comment by phyber** [comment]
Ahh, thanks. I'm surprised Cargo let me pull the crate in!

Case closed :)

**Comment by dignifiedquire** [comment]
Sorry about this, `v.0.10.1` is out now and should fix these issues

**Comment by phyber** [comment]
Thanks a lot for the quick fix. It looks good from here, my tests pass again :)
