### ISSUE TITLE
How to check whether a file is literal or encrypted (armored or bytes)?

### ISSUE THREAD

**Issue by 0cv** [rpgp/rpgp#243]
The method to load a file seems to assume that a file must already have the right format (e.g. be armored), and I'm not sure how it would be possible to verify whether that file is encrypted at all, or whether it's armored or it has bytes instead.

In this code below, if `string_encrypted` is actually not encrypted but some random text, `Message::from_armor_single` will return an error. That seems unexpected to me because, `message` may be a `Message::Literal`.

```rust
let cursor_encrypted = Cursor::new(&string_encrypted);
let (message, _) = Message::from_armor_single(cursor_encrypted)?;
```

Is there maybe a more generic method to build a `Message` ?

**Comment by dignifiedquire** [comment]
Support for this was added in https://github.com/rpgp/rpgp/pull/311
