### ISSUE TITLE
Changed API after upgrading from 0.9.0 to 0.10.2

### ISSUE THREAD

**Issue by LiveDuo** [rpgp/rpgp#248]
Hey, thanks for the work you put into this project.

I'm trying to upgrade the crate from `0.9.0` to `0.10.2` and I'm encountering two issues.

The first problem is that `key_id()` method is not found on `pgp::packet::key::SecretKey` while it was previously working. The rust analyzer suggest I bring `use pgp::types::key::KeyTrait;` in scope but that's private. Previously the `key_id()` method worked from by bringing `use pgp::types::KeyTrait;` in but that's no longer the case.

<img width="720" src="https://github.com/rpgp/rpgp/assets/370612/17914ad2-5575-4100-8ea0-6471bc17538d">

The second problem is that the `pgp::StandaloneSignature` verify function does no longer accept `pgp::SignedSecretKey` as the first parameter. Again, previously working flawlesly.

<img width="720" src="https://github.com/rpgp/rpgp/assets/370612/37d76d85-4a78-4052-9983-99b91c2887ac">

I'm not sure if these are intended behaviours and will be happy to hear any ideas to get these sorted.

**Comment by LiveDuo** [comment]
My bad. Everything works as expected. Had an issue with two `rpgp` version in different crates in the same workspace.

**Comment by dignifiedquire** [comment]
glad to hear it worked out
