### ISSUE TITLE
Error after make on OSX 10.12

### ISSUE THREAD

**Issue by nicodh** [rpgp/rpgp#28]
When I run make in /pgp-ffi/ I get an error: 
`/Users/me/rpgp/pgp-ffi/../ && cargo test --release -p pgp_ffi
error: failed to parse manifest at /Users/me/rpgp/Cargo.toml`
`Caused by:
  feature 'rename-dependency' is required
`

I have cargo 1.30.0
I had no rust installed (it was installed by running make)

**Comment by dignifiedquire** [comment]
Hmm `make` doesn't install rust, so not sure where your rust version is coming from. 

Can you run `rustc --version` for me?

**Comment by nicodh** [comment]
rustc 1.32.0
- probably outdated...

**Comment by nicodh** [comment]
I upgraded to rustc 1.34.0-nightly (aadbc459b 2019-02-23) now 
- but still the same error...

**Comment by dignifiedquire** [comment]
what commit are you on? (of this repo)

**Comment by nicodh** [comment]
was on ed36f7ad4498b606298ca7bc4d21060d96bb63ff
just updated to 348b7c62bb09a188274d3bf659db20b861748d88

same error. Do I have to clean/clear something after updating the sources?

**Comment by dignifiedquire** [comment]
This makes very little sense the `rename-dependency` feature is nowhere near the current version. Can you grep the whole repo for `rename-dependency`?

**Comment by dignifiedquire** [comment]
maybe try running `cargo update` that could help

**Comment by nicodh** [comment]
It didn't.
and grep didn't find "rename-dependency"

**Comment by dignifiedquire** [comment]
can you check what `cargo --version` prints for you in that directory, there might be a missmatch there

**Comment by nicodh** [comment]
it's always 1.30.0

**Comment by dignifiedquire** [comment]
That's likely the issue. To fix that you probably need to get rid of all the cargo/rust installations and do a clean install using rustup, as described here: https://www.rust-lang.org/tools/install

**Comment by hpk42** [comment]
On Mon, Mar 25, 2019 at 05:20 -0700, Friedel Ziegelmayer wrote:
> That's likely the issue. To fix that you probably need to get rid of all the cargo/rust installations and do a clean install using rustup, as described here: https://www.rust-lang.org/tools/install

Maybe add this last sentence/advise to the README?

**Comment by nicodh** [comment]
That was the problem. After reinstalling all went as expected...
