### ISSUE TITLE
Add support for additional ECC curves

### ISSUE THREAD

**Issue by hko-s** [rpgp/rpgp#288]
Specifically: p521, bp256, bp384

**Comment by dignifiedquire** [comment]
oh nice, yes we should add support for these, now that they are implemented in rustcrypto

**Comment by hko-s** [comment]
An update: p521 is now available for use with ecdsa via #304.

The current 0.6 versions of bp256 and bp384 seem tricky/not ready to use in rpgp. Seems to me these crates don't yet implement everything we need to use them in the same way that we use the nistp crates. For example, `bp256::BrainpoolP256r1` doesn't implement `elliptic_curve::CurveArithmetic`.

I think the pragmatic way forward is to wait for more progress on the brainpool crate to land.

**Comment by hko-s** [comment]
nist p curves for ecdh are added in https://github.com/rpgp/rpgp/pull/351.

**Comment by dignifiedquire** [comment]
This is done
