### ISSUE TITLE
Could use sha1collisiondetection

### ISSUE THREAD

**Issue by hko-s** [rpgp/rpgp#293]
When computing SHA1 hashes, detecting collision attacks could serve as one layer of defense.

**Comment by wiktor-k** [comment]
Note that the crate has been translated from C to Rust via c2rust: https://crates.io/crates/sha1collisiondetection and as such is not a marvel of technical design.

It would be cool if that was natively supported by the sha1 crate (sadly a quick look through the issues doesn't get my hopes high).

**Comment by dignifiedquire** [comment]
Started work on this here: https://github.com/dignifiedquire/hashes/tree/feat-sha1-collision

**Comment by dignifiedquire** [comment]
Basic tests are now passing. Mostly needs some api design now and adding the rest of the tests.

**Comment by wiktor-k** [comment]
Wow, that's great! Based on my research quite a lot of people are waiting for this so... much appreciated 🙇‍♂️

**Comment by dignifiedquire** [comment]
WIP PR is now up: https://github.com/RustCrypto/hashes/pull/566

**Comment by dignifiedquire** [comment]
@wiktor-k thanks for all the background work, made it a lot easier for me to pull things together :)

**Comment by hko-s** [comment]
I believe SHA-1 comes up in three contexts in OpenPGP:

1. [v4 Fingerprints](https://www.rfc-editor.org/rfc/rfc4880.html#section-12.2)
2. Hashing input data for a signature packet
3. Modification Detection Code (MDC) in [SEIPDv1](https://www.rfc-editor.org/rfc/rfc4880.html#section-5.13)

My understanding is that collisions are a concern for the first two, but not so much for the third (MDC).

I suggest rpgp should use [sha1-checked](https://crates.io/crates/sha1-checked) for 1. and 2.
I suggest not using it for 3.

Reasoning:

1. Fingerprints are calculated over tiny amounts of data, I assume the cost of using sha1-checked is negligible. It seems well worth paying.
2. SHA-1 used in OpenPGP signatures should be considered legacy/historical at this point. There are two subcases:
  - Binding signatures (and similar) are over small amounts of data, so the added cost of sha1-checked is negligible (using sha1-checked seems worthwhile, and should be cheap),
  - Data signatures can be over non-trivial amounts of data, so the cost of using sha1-checked can be non-trivial. However, hashing in data signatures in OpenPGP has shifted to using SHA2 very long ago, mostly. Data signatures that use SHA-1 are either historical, and/or suspect. The (rare) cost of using sha1-checked to verify SHA-1-based data signatures seems well worth spending to me.

MDC in SEIPDv1 (point 3 in the list above) however, will keep using SHA-1, as long as SEIPDv1 is used. It is my understanding that collisions are not a concern in that construction. Also, the amount of hashed data may be substantial. So the cost of using sha1-checked for MDC can be non-trivial.
Based on my current understanding, I don't think it's worth paying the cost for collision detection in MDC.

**Comment by hko-s** [comment]
I'm implementing the above approach in https://github.com/rpgp/rpgp/pull/353

**Comment by dignifiedquire** [comment]
Fixed in https://github.com/rpgp/rpgp/pull/353
