### ISSUE TITLE
Make a new rPGP release

### ISSUE THREAD

**Issue by link2xt** [rpgp/rpgp#295]
We plan to release Delta Chat 1.44 soon and for that need to update rPGP in the core.
All the necessary rPGP fixes that we want to get into release are now merged, so we only need a new tag and crates.io release to update.

cc @dignifiedquire

**Comment by wiktor-k** [comment]
There are a couple of PRs that look like "done" (but not "done-done"?) and maybe it'd be good to push them through the finishing line before cutting the release...?

**Comment by dignifiedquire** [comment]
yes, I will cut once the main open PRs are merged

**Comment by dignifiedquire** [comment]
release is out, and now with a nicer changelog: https://github.com/rpgp/rpgp/releases/tag/v0.11.0
