### ISSUE TITLE
Please add a link in GitHub project settings

### ISSUE THREAD

**Issue by wiktor-k** [rpgp/rpgp#297]
The "add repository details" button (cogwheel symbol on the right) shows a "website" field and I think it would be good if it pointed to https://crates.io/crates/pgp (or, alternatively to https://docs.rs/pgp ).

This may be minor but I'm so used to clicking and discovering sites by links :sweat_smile: 

Thanks in advance! :bow:

**Comment by dignifiedquire** [comment]
done
