### ISSUE TITLE
Repo is quite big

### ISSUE THREAD

**Issue by Jikstra** [rpgp/rpgp#35]
The repository is quite big, currently cloning and it seems like it's around 1gb. If i remember it correctly there's some huge test data laying around, can we remove that or move it into another repository? Or any other ideas? I'm currently building -desktop on various platforms and cloning 1gb of data every time is no fun :D

**Comment by hpk42** [comment]
On Wed, Mar 27, 2019 at 12:52 +0000, Jikstra wrote:
> The repository is quite big, currently cloning and it seems like it's around 1gb. If i remember it correctly there's some huge test data laying around, can we remove that or move it into another repository? Or any other ideas? I'm currently building -desktop on various platforms and cloning 1gb of data every time is no fun :D

you can do "git clone --depth 1" and this results in 3.8MB downloaded.

**Comment by hpk42** [comment]
But i think it's better to trim down rpgp's history.  It's such a small nice library and the first impression is "WTF is it taking so long?". Bad onboarding UX ;)

**Comment by Jikstra** [comment]
> you can do "git clone --depth 1" and this results in 3.8MB downloaded.

Very helpful, thanks :)

**Comment by dignifiedquire** [comment]
![Screenshot 2019-03-28 at 21 00 22](https://user-images.githubusercontent.com/790842/55188841-92bb3080-519c-11e9-9de5-8cc7671ede9e.png)

Fixed

**Comment by dignifiedquire** [comment]
![Screenshot 2019-03-28 at 21 06 13](https://user-images.githubusercontent.com/790842/55189179-7ec3fe80-519d-11e9-957a-26f4fa9e0036.png)
![Screenshot 2019-03-28 at 21 06 09](https://user-images.githubusercontent.com/790842/55189181-7ec3fe80-519d-11e9-8d24-479a47e79008.png)

**Comment by hpk42** [comment]
great, thanks!
