### ISSUE TITLE
There may be a bug public.rs, please see code section with comment.

### ISSUE THREAD

**Issue by godadada** [rpgp/rpgp#37]
PublicParams::ECDSA { ref curve, ref p } => f
                .debug_struct("PublicParams::ECDSA")
                .field("curve", curve)
                .field("p", &p)
                .finish(),
            PublicParams::ECDH {
                ref curve,
                ref p,
                hash,
                alg_sym,
            } => f
                .debug_struct("PublicParams::ECDSA")
                                                              // Should be ECDH?
                .field("curve", curve)
                .field("hash", hash)
                .field("alg_sym", alg_sym)
                .field("p", &p)
                .finish(),
PublicParams::Elgamal {

**Comment by dignifiedquire** [comment]
Yes, looks like it. Want to make a PR?
