### ISSUE TITLE
Decrypting file with secret key outputs content prefixed with header

### ISSUE THREAD

**Issue by DoumanAsh** [rpgp/rpgp#378]
Subj

Using [Message::decrypt](https://docs.rs/pgp/0.13.1/pgp/composed/message/enum.Message.html#method.decrypt) I can decode file encrypted with pgp.
But when I attempt to deserialize file, I found out that it includes PGP header together with file name before hitting content.

I can say for sure it happens with compressed data https://docs.rs/pgp/0.13.1/pgp/composed/message/enum.Message.html#variant.Compressed
But I'm not sure if it is intended or not.

If it is, then API is kinda bad

**Comment by DoumanAsh** [comment]
Nevermind, it seems user should use [get_content](https://docs.rs/pgp/0.13.1/pgp/composed/message/enum.Message.html#method.get_content) rather than [CompressedData](https://docs.rs/pgp/0.13.1/pgp/packet/struct.CompressedData.html) directly

**Comment by hko-s** [comment]
Just to drop some context here for interested readers: Encrypted OpenPGP messages are defined to contain an OpenPGP message (i.e. their structure is recursive): https://www.rfc-editor.org/rfc/rfc4880#section-11.3

An encrypted OpenPGP message may recursively contain: yet another layer of encryption, a signature layer, a compression layer, or finally: "literal data". Each of the first three can in turn can contain any of them, so in principle the recursion can be arbitrarily deep. That's just the nature of the OpenPGP format.

rPGP is a low level library, so it has to allow programmatic access to this structure. For some applications, it is important to have "verbatim" access the inner message in an encrypted container (and not just the eventual inner cleartext payload). Which can unfortunately be confusing without understanding OpenPGP's internals.

However, if you just need the decrypted payload, as you write, `Message::get_content` is a convenience function that hides some of the format's complexity (at the cost that e.g. signature layers that might be inside an encrypted message are effectively ignored).
