### ISSUE TITLE
AUR package published

### ISSUE THREAD

**Issue by Jikstra** [rpgp/rpgp#38]
Not sure where else to announce this, i built a simple PKGBUILD to create and install an archlinux package for this lib. Maybe an Install/Building section would be good?
https://aur.archlinux.org/packages/rpgp-git/

**Comment by dignifiedquire** [comment]
Cool, does this require republishing on every change?

**Comment by Jikstra** [comment]
Currently yes because i do a shallow clone and can't get the latest tag (git tags are not included in a shallow clone). Therefore i hardcoded it.

**Comment by hpk42** [comment]
On Wed, May 22, 2019 at 11:42 -0700, Jikstra wrote:
> Currently yes because i do a shallow clone and can't get the latest tag (git tags are not included in a shallow clone). Therefore i hardcoded it.

for me cloning rpgp takes 3-4 secs but apparently for jikstra it's different
which is why he does only a shallow clone.

**Comment by hpk42** [comment]
that's fixed by now IIRC.  if not @jikstra, please speak up and re-open/open fresh.
