### ISSUE TITLE
Encode Message into raw format

### ISSUE THREAD

**Issue by DoumanAsh** [rpgp/rpgp#382]
Message provides API to create armored message, but otherwise there seems to be no way to create raw bytes message that can be decoded using https://docs.rs/pgp/0.13.1/pgp/composed/trait.Deserializable.html#method.from_bytes

While it might be not a priority but it would be convenient to create Gnu GPG like messages (since this format is default one)

**Comment by hko-s** [comment]
I think you want to serialize a Message in binary format (not ascii armored).
You can do that like [here](https://docs.rs/rpgpie/latest/src/rpgpie/msg/mod.rs.html#493) by using `Message::to_writer`.

**Comment by DoumanAsh** [comment]
Ah I see, it was separate trait, not part of Message API...
My bad, traits are kinda bad for public visibility 🙇 

On side note, is there way to correctly apply compression on encrypted message?

Should I compress then encrypt or vice versa? 🤔

**Comment by hko-s** [comment]
> On side note, is there way to correctly apply compression on encrypted message?
> 
> Should I compress then encrypt or vice versa? 🤔

Encrypted data has high entropy and is thus effectively impossible to compress. If there is any hope of "making your data smaller", it needs to be compressed before encryption.
