### ISSUE TITLE
Fix `test_many_parser` test

### ISSUE THREAD

**Issue by wiktor-k** [rpgp/rpgp#400]
Currently `test_many_parser` (in `src/packet/many.rs`) requires an sks-dump file and fails if that's unavailable.

I think it's surprising for people rarely looking at the source who just want `cargo test` to succeed.

I propose one of two solutions:
1. Make the test pass if the file is not there.
2. Mark the test as `#[ignore]` (excluding time-consuming tests is apparently [the intended use case](https://doc.rust-lang.org/book/ch11-02-running-tests.html#ignoring-some-tests-unless-specifically-requested)). The CI already runs ignored tests so it wouldn't need any change.

If there's a consensus on the approach I'm happy to file a PR.

Thanks for your time! :wave:

**Comment by dignifiedquire** [comment]
fixed in https://github.com/rpgp/rpgp/pull/396

**Comment by wiktor-k** [comment]
Just noticed it has been fixed in 1c0cd841 after pulling the updates. Great! :tada:
