### ISSUE TITLE
Can we make a new git tag?

### ISSUE THREAD

**Issue by Jikstra** [rpgp/rpgp#41]
Cloning from a specific commit is not that easy (sure it is, it just needs 2 git commands but i need to update all ci scripts for this), having a git tag would be easier.

**Comment by dignifiedquire** [comment]
git tags happen with cargo publishes. why do you need two commands? for checking out a commit?

**Comment by Jikstra** [comment]
Yup. We can't clone a git repo from a specific commit, this only works for a branch/tag.

**Comment by Jikstra** [comment]
@dignifiedquire what's blocking on making a new version?

**Comment by dignifiedquire** [comment]
that I don’t have anything on master to publish to crates.io and tags should match released versions

**Comment by hpk42** [comment]
i think things are released by now ... and will be released afresh soon ;)
