### ISSUE TITLE
unexpected block type: PGP SIGNED MESSAGE

### ISSUE THREAD

**Issue by JonasVautherin** [rpgp/rpgp#429]
I am trying the [first example from the README](https://github.com/rpgp/rpgp?tab=readme-ov-file#load-a-public-key-and-verify-an-inline-signed-message), with the following msg.asc:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

hello, test
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEE4JQoCLcEK076omaW2amCbuN/p44FAmcbgqsACgkQ2amCbuN/
p478ZA//Vit/qGdQBYMmo0sXF8b5qSkKyIeOU/T5FhdplxoQe8ii+RKVgknkWQQh
[...]
Q5l3P2upzjUUEcay0Dzh84i4ThJwIlgu2TU9c96OlxtITl281z43iBT1OqCXW2Ub
oTtYszkpon+yKaiF9m5AHot96BNxhTSEvWZQdKQyCmikigA3xdf6k8Ng6X5w9VQi
=uLUn
-----END PGP SIGNATURE-----
```

When I run the example, I get the error:

```rust
Message("unexpected block type: PGP SIGNED MESSAGE")
```

from this line:

```rust
let (msg, _headers_msg) = Message::from_string(&msg_string).unwrap();
```

What am I doing wrong? Isn't my inline-signed message properly formed?

**Comment by hko-s** [comment]
`CleartextSignedMessage::from_string` should work for this case.

(Cleartext signed messages are an odd format, they are not modeled as `Message` objects in rPGP.)

**Comment by JonasVautherin** [comment]
Thanks for the super quick answer! So I should actually generate the inline-signed message with: `gpg --armor --sign > msg.asc`, right?

It goes further but now fails with:

```
Message("verify: No matching issuer or issuer_fingerprint for Key ID: KeyId(<id>)")
```

at this line:

```rust
msg.verify(&public_key).unwrap();
```

Is that related to the comment "NOTE: This assumes that the primary serves as the signing key, which is not always the case!"? I have a subkey for signing...

**Comment by hko-s** [comment]
Right, if you want to use `Message`, in rPGP, then it sounds like that `gpg` command produces the right output (I'm not fluent in gpg's CLI :sweat_smile: )

As you suspect: to verify, you need to use the correct component key - in your case, the correct subkey.
rPGP has a very low level API, so operations on the OpenPGP semantics layer are relatively verbose to do (e.g. finding the signing subkey, making sure it's not expired, etc ..).

I'm experimenting with a wrapper API that exposes the OpenPGP semantics layer, at https://crates.io/crates/rpgpie. But that project is still in an early phase. For example uses of rpgpie, the https://crates.io/crates/rsop CLI tool is relatively complete (but also still in a rather early development phase).

**Comment by wiktor-k** [comment]
> I can't speak to OpenPGP card usage on Android. I'm unsure what exactly it would take to access the device.

It's certainly possible, as evidenced by https://github.com/DDoSolitary/OkcAgent

I was looking at adding support for devices passed as file descriptors to PCSC (as Android lets applications receive USB devices like that). I didn't succeed but I came to the conclusion that maybe PCSC could just be removed from the equation and the file descriptor could be written to via `openpgp-card-rpgp` directly? (this would probably require some changes to the library). If my understanding is correct PCSC is especially useful for desktop systems for management of multiple connected cards and their state changes but Android doesn't use this kind of architecture.

I think this could be tested on desktop systems too by using `/sys` devices.

Sorry I can't help more!

**Comment by JonasVautherin** [comment]
That's very interesting! I am pretty sure I can find a way to pass a file descriptor to a USB device from Java/Kotlin to C++ over JNI. I assume I should eventually manage to do that with Rust (I assume it's very similar, through the FFI).

I am not very familiar with PCSC and how the communication works with the hardware key. I guess `openpgp-card-rpgp` doesn't just take a file descriptor as an argument, or does it? I guess I need to look into the source code of `openpgp-card-rpgp`, but if you have pointers there that would be appreciated! No pressure though, first I need to prove that I can correctly pass the file descriptor to C++/Rust 😊.

**Comment by wiktor-k** [comment]
I think passing descriptors will be the easiest part (since it's just a number) and on Rust side you can definitely create a `UnixStream` from a descriptor via [`UnixStream::from_raw_fd`](https://doc.rust-lang.org/nightly/std/os/unix/net/struct.UnixStream.html#impl-FromRawFd-for-UnixStream]). (or maybe you need [`File::from_raw_fd`](https://doc.rust-lang.org/nightly/std/fs/struct.File.html#impl-FromRawFd-for-File)?)

The library which does the cards communication (`openpgp-card`) has pluggable backends. One of them does communication via PCSC but I think you should build another based on the `scdc` backend (which is very short). In the nutshell there's one central function called [`transmit`](https://gitlab.com/openpgp-card/openpgp-card/-/blob/main/scdc/src/lib.rs?ref_type=heads#L241) which, in your case, you'd have to write to the `UnixStream` socket / file and read from it.

Note that this is based on my early view and may be incorrect here on there :sweat_smile: If you find any problems along the way I'm happy to suggest something (sadly I'm quite stuffed with coding work so I can't help with this directly :( ).

**Comment by hko-s** [comment]
I'll mostly defer to @wiktor-k here, and just try to clarify the exact crates and traits he's referring to:

https://crates.io/crates/card-backend

defines the (very simple) backend traits, which is used by the https://crates.io/crates/openpgp-card layer (which, in turn, is what's underlying https://crates.io/crates/openpgp-card-rpgp).

You probably want to figure out how to talk to card on Android, and implement the `card-backend` trait for Android. Plugging that into `openpgp-card-rpgp` should hopefully be trivial, then.

**Comment by JonasVautherin** [comment]
> I think passing descriptors will be the easiest part (since it's just a number)

It looks like it's just an int, but it's not: there is some kind of conversion to do between the Java wrapper FileDescriptor and the Unix file descriptor (apparently Android 31 added a helper for that: https://developer.android.com/ndk/reference/group/file-descriptor). I tried to just pass an int in the past and it was not enough, so I'll try the conversion.

For the rest, thanks again for all the pointers! I'll look into it in my own time and will open a new issue as soon as I have news to share with you. Let's see how far I can go!

**Comment by hko-s** [comment]
Great. All the best, and do keep us posted!

**Comment by wiktor-k** [comment]
> For the rest, thanks again for all the pointers! I'll look into it in my own time and will open a new issue as soon as I have news to share with you. Let's see how far I can go!

Just a couple more details on what may be useful to check: https://wiki.termux.com/wiki/Termux-usb This asks for access to the USB device and passes it as a file descriptor (but I didn't see the source code anywhere :/ ) (just in case it's not clear it's a plugin to the [termux terminal](https://f-droid.org/packages/com.termux/)).

I wrote a small example of [file based backend to OpenPGP Card](https://gitlab.com/wiktor/openpgp-card/-/commit/f04a41dec72020e52f205b4ba740ea4ec6967c09) but now I'm thinking maybe pcsc adds more framing to what openpgp-card is sending so this may not be super-easy... maybe it'll be useful for you as a starting point.

That's my 2 cents. Have a nice day! :) :wave:

**Comment by wiktor-k** [comment]
One last thing I forgot to mention: There's already one working project that accesses card on Android: OpenKeychain (https://github.com/open-keychain/open-keychain). Even though it's unmaintained you may take a look at what they're doing in case your run into problems.
