### ISSUE TITLE
Loading keys

### ISSUE THREAD

**Issue by SOF3** [rpgp/rpgp#44]
KeyType implements Serialize which offres a to_bytes function, but there doesn't appear to be a function to load such serialization.

**Comment by dignifiedquire** [comment]
there are various ways to import keys, for example from a string like here: https://github.com/rpgp/rpgp/blob/master/tests/key_test.rs#L143

**Comment by SOF3** [comment]
Are they compatible with the format on KeyType or SecretKey? The various key generation and serialization methods are confusing.
