### ISSUE TITLE
Invalid handling of encoding when decrypting

### ISSUE THREAD

**Issue by 0xpr03** [rpgp/rpgp#50]
Hello,
while trying to decrypt a message I stumbled upon errors in the handling of UTF-8 data.

I attached the test message generated by opengpgjs. I can decrypt this totally fine with gpg shipped in ubuntu 18.04. When decrypting this here I get `{"secret":"â¦Â·â^Â¨Ë~Ã¼Ã¶Ã¤-.,#+"}`.
The input is `{"secret":"…·–^¨˝’~üöä-.,#+"}`

[test_message.zip](https://github.com/rpgp/rpgp/files/3693406/test_message.zip)
Key password: `asd`

[Test Code](https://gist.github.com/0xpr03/b4d6087c0487e9afc04bc66b615bff35)

Oh and also your docs.rs are not building currently.

**Comment by 0xpr03** [comment]
Note that this is due to a bug in LiteralData::toString().
As pointed out on IRC it's iterating over the bytes turning them into ASCII instead of something like
```rust
let data: LiteralData ..
let my_string_data = std::str::from_utf8(data.data())?;
```

**Comment by Moongoodboy** [comment]
```
diff --git a/src/packet/literal_data.rs b/src/packet/literal_data.rs
index 2feff2d..f5968b7 100644
--- a/src/packet/literal_data.rs
+++ b/src/packet/literal_data.rs
@@ -84,7 +84,7 @@ impl LiteralData {
     pub fn to_string(&self) -> Option<String> {
         match self.mode {
             DataMode::Binary => None,
-            _ => Some(self.data.iter().map(|c| *c as char).collect()),
+            _ => std::str::from_utf8(&self.data).map(str::to_owned).ok(),
         }
     }
 }
```

Of note is the fact that this method could actually return `Option<&str>`, skipping allocation and copying.

Another consideration: what if `mode` is `Binary`, but `data` actually contains valid UTF-8 text? I'm not familiar with PGP, but this seems like a potential pitfall and should probably at least be documented:

```
diff --git a/src/packet/literal_data.rs b/src/packet/literal_data.rs
index 2feff2d..35d7a4c 100644
--- a/src/packet/literal_data.rs
+++ b/src/packet/literal_data.rs
@@ -81,6 +81,9 @@ impl LiteralData {
     }
 
     /// Convert the data to a string, if appropriate for the type.
+    ///
+    /// Returns `None` if `self.is_binary()`; otherwise, returns the data as a `String` if
+    /// it is valid UTF-8.
     pub fn to_string(&self) -> Option<String> {
         match self.mode {
             DataMode::Binary => None,
```

…although, in my opinion, this method should just be deprecated altogether, leaving it up to the caller to use `LiteralData::data()` and convert it into a string if they want. (And deprecation might be preferred if this is considered too breaking of a fix.)

**Comment by dignifiedquire** [comment]
Thanks, I pulled in those changes in #52

**Comment by dignifiedquire** [comment]
> although, in my opinion, this method should just be deprecated altogether, leaving it up to the caller to use `LiteralData::data()` and convert it into a string if they want.

I am happy to leave it as a convenience method for now.
