### ISSUE TITLE
Support for DSA and ElGamal

### ISSUE THREAD

**Issue by HeikoStamer** [rpgp/rpgp#56]
Currently, DSA and ElGamal (encrypt-only) are still MUST algorithms of RFC4880. Are there any plans to support them for reasonable key sizes (i.e. >= 2048/256)?

**Comment by dignifiedquire** [comment]
I would like to add support, but this first requires implementing them in pure Rust, which I currently do not have time for unfortunately.

**Comment by HeikoStamer** [comment]
I cannot help with code, because I am not familiar with Rust. However, I can answer questions regarding cryptographic background of DSA and ElGamal.

**Comment by link2xt** [comment]
It needs to be implemented in RustCrypto, rpgp already depends on crates aes, block-modes etc. which are part of this project.

DSA goes into https://github.com/RustCrypto/signatures/ and ElGamal is better implemented in its own repository similar to https://github.com/RustCrypto/RSA (authored by @dignifiedquire btw).

**Comment by tarcieri** [comment]
There's a @RustCrypto `dsa` crate available now: https://github.com/RustCrypto/signatures/tree/master/dsa

**Comment by dignifiedquire** [comment]
dsa support & elgamal verification are implemented
