### ISSUE TITLE
Implement EdDSA encryption

### ISSUE THREAD

**Issue by link2xt** [rpgp/rpgp#66]
It prevents usage of ECC keys in Delta Chat, leading to issues like this: https://github.com/deltachat/deltachat-core-rust/issues/802 Keys are imported successfully, but an attempt to send a message to myself in DC command line client results in this error:
```
> send Hi!
[DC_EVENT_ERROR] PGP: Unimplemented("encryption with EdDSA")
{Received MsgFailed { chat_id: 25, msg_id: MsgId(1000) }}
Error: PGP: Unimplemented("encryption with EdDSA")
```

ECC keys support is also needed to resolve https://github.com/deltachat/deltachat-core-rust/issues/509

Going to try implementing it.

**Comment by dignifiedquire** [comment]
EdDSA is a signature algorithm, I believe there is an issue in key selection rather than an actual missing implementation here.

**Comment by link2xt** [comment]
Indeed, I can manually select ECDH PublicSubkey from exported public key, but DC somehow selects EdDSA public key for encryption.

**Comment by dignifiedquire** [comment]
@link2xt can we close this issue?
