### ISSUE TITLE
Using RPGP on iOS

### ISSUE THREAD

**Issue by oliverFU** [rpgp/rpgp#91]
Hey,

your code looks great and we would like to use your lib in our Open-Source PGP mail client on iOS (Letterbox, https://git.imp.fu-berlin.de/enzevalos/enzevalos_iphone). Unfortunately, in your current version pgp-ffi is missing. Do you plan add this again?

Thanks and best
Oliver

**Comment by dignifiedquire** [comment]
The pgp-ffi crate was written to support a specific use case and was missing a lot of functionality, which is why I removed it for now. 

If there is interest in reviving a C-API I think we could take the old code and put it into its own repo under rpgp/rpgp-c-ffi

**Comment by oliverFU** [comment]
Thanks for your fast feedback. 
It sounds good. Currently we are testing a deprecated pgp-ffi file.
