### ISSUE TITLE
Signing based on `Read` trait instead of slices

### ISSUE THREAD

**Issue by drahnr** [rpgp/rpgp#99]
It would be advantageous to provide a way to sign multiple existing slices.
The easiest way would be to introduce API consuming a `R: Read` type which the user can than implement as desired. Otherwise, especially if parsing chunked external data, it would be necessary to copy the data.

**Comment by dignifiedquire** [comment]
Yes, makes sense to add this. The only thing we likely need to be careful is how to specify the lenght.
